spring.application.name=course-management
spring.datasource.url=jdbc:postgresql://localhost:5432/course_management
spring.datasource.username=postgres
spring.datasource.password=S1mpL0rd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
